### PR TITLE
Catalan admin UI translation

### PR DESCRIPTION
**Pull request by davefv**
## Ticket

No ticket created

## Summary

What does this PR do/solve? 

Translate admin UI to catalan. This language is supported in the latests versions of Strapi

## Test Plan

Configure src/admin/app.js file to use Catalan language:
```
export default {
  config: {
    locales: ['ca'],
  },
  bootstrap() {},
};
```

### CODE REVIEW

**Comment by CodeVoyager** [comment]
FYI @davefv following keys are missing from your version but available in EN version on `master`

popup.navigation.manage.navigation.visible, popup.navigation.manage.navigation.hidden, notification.error.customField.type, pages.settings.customFields.title, pages.settings.form.pathDefaultFields.label, pages.settings.form.pathDefaultFields.placeholder, pages.settings.form.pathDefaultFields.hint, pages.settings.form.pathDefaultFields.empty, pages.settings.form.customFields.table.confirmation.header, pages.settings.form.customFields.table.confirmation.message, pages.settings.form.customFields.table.confirmation.confirm, pages.settings.form.customFields.table.confirmation.error, pages.settings.form.customFields.table.header.name, pages.settings.form.customFields.table.header.label, pages.settings.form.customFields.table.header.type, pages.settings.form.customFields.table.header.required, pages.settings.form.customFields.table.footer, pages.settings.form.customFields.table.edit, pages.settings.form.customFields.table.enable, pages.settings.form.customFields.table.disable, pages.settings.form.customFields.table.remove, pages.settings.form.customFields.table.required, pages.settings.form.customFields.table.notRequired, pages.settings.form.customFields.popup.header.edit, pages.settings.form.customFields.popup.header.new, pages.settings.form.customFields.popup.name.label, pages.settings.form.customFields.popup.name.placeholder, pages.settings.form.customFields.popup.name.description, pages.settings.form.customFields.popup.label.label, pages.settings.form.customFields.popup.label.placeholder, pages.settings.form.customFields.popup.label.description, pages.settings.form.customFields.popup.type.label, pages.settings.form.customFields.popup.required.label, pages.settings.form.customFields.popup.required.description, pages.settings.form.customFields.popup.options.label, pages.settings.form.customFields.popup.options.description, pages.settings.form.customFields.popup.multi.label

**Comment by cyp3rius** [comment]
@davefv will you be able to provide missing translations? Otherwise, we will reject this PR.

**Comment by davefv** [comment]
@cyp3rius I have updated the translation. I hope it's correct now. Thank you!

**Review by cyp3rius — APPROVED** [review]

**Comment by cyp3rius** [comment]
Thanks @davefv, today afternoon we're planning to release major and beta versions of our plugin. Both will include your PR :)

**Comment by davefv** [comment]
Great! Thank you very much @cyp3rius !

**Pull request merged**
