### PR TITLE
feat: remove polymorphic relation

### PR DESCRIPTION
**Pull request by Kronos66**
## Ticket

https://github.com/VirtusLab/strapi-plugin-navigation/issues/-<your-ticket-#>

## Summary

What does this PR do/solve? 

> PRs should be as small as they need to be, if this section starts becoming a novel you should _seriously_ consider breaking it up into multiple PRs

## Test Plan

How are you testing the work you're submitting?

### CODE REVIEW

**Comment by huseyinalp** [comment]
Hello @Kronos66 ;
I have merged your PR to my fork and seems that it throws an error like below:
`[2021-09-05T22:20:14.286Z] error Something went wrong in the model `Navigationitem` with the attribute `localizations`
[2021-09-05T22:20:14.286Z] error TypeError: Cannot read property 'uid' of undefined`

For your information.
Thanks

**Comment by Kronos66** [comment]
> Hello @Kronos66 ;
> I have merged your PR to my fork and seems that it throws an error like below:
> `[2021-09-05T22:20:14.286Z] error Something went wrong in the model `Navigationitem`with the attribute`localizations` [2021-09-05T22:20:14.286Z] error TypeError: Cannot read property 'uid' of undefined`
> 
> For your information.
> Thanks

Hi, @huseyinalp in the meantime I working on localization for navigation and I forgot to remove the model modification.... sorry for this. Today I will push the version without that modification and everything should start work :)

**Comment by huseyinalp** [comment]
Hi @Kronos66;
Thank you for your reply. Actually, I also need localization. When do you think localization can be ready ?
Our aim is that display different navigation for two locales. I guess we have two possible solution for that. First one is that supporting localization and another way is that adding multiple navigation. I have seen somebody added new navigation calling as header and footer navigation but I couldn't see any instruction for that. Does it support nativelly on this plugin  or is it custom implementation ?

Thanks
Huseyin

**Comment by Kronos66** [comment]
Yes, I saw that solution but in that case we had other problem with polymorphic relation - that relation allow assign only one element from content types to navigation item - this a reason why we drop that relation and wrote our implementation. I hope localization for navigation will be finish in 2 weeks :).

**Comment by HazemKhaled** [comment]
I believe you like to help here @anouarkacem

**Pull request merged**
